export const GET_ERRORS = "GET_ERRORS";
export const GET_SIMPLE_RETURNS = "GET_SIMPLE_RETURNS";
export const GET_LOGARITHMIC_RETURNS = "GET_LOGARITHMIC_RETURNS";
export const LOAD_PORTFOLIO_RETURNS = "LOAD_PORTFOLIO_RETURNS";
